/** biome-ignore-all lint/suspicious/noExplicitAny: yes */
// disclaimer: this test was generated by claude code
import { expect, test, spyOn, beforeEach, afterEach } from "bun:test";
import { LoggerModule } from "../../src";

let logger: LoggerModule;
let logSpy: any;
let warnSpy: any;
let errorSpy: any;
let debugSpy: any;

beforeEach(() => {
	logger = new LoggerModule();
	logSpy = spyOn(console, "log").mockImplementation(() => {});
	warnSpy = spyOn(console, "warn").mockImplementation(() => {});
	errorSpy = spyOn(console, "error").mockImplementation(() => {});
	debugSpy = spyOn(console, "debug").mockImplementation(() => {});
});

afterEach(() => {
	logSpy.mockRestore();
	warnSpy.mockRestore();
	errorSpy.mockRestore();
	debugSpy.mockRestore();
});

test("notif() calls console.log and respects raw flag", () => {
	logger.notif("test message");
	expect(logSpy).toHaveBeenCalled();
	expect(logSpy.mock.calls[0][0]).toContain("NOTIF");
	expect(logSpy.mock.calls[0][0]).toContain("test message");

	const raw = logger.notif("raw message", true);
	expect(typeof raw).toBe("string");
	expect(raw).toContain("raw message");
});

test("alert() calls console.warn", () => {
	logger.alert("warning message");
	expect(warnSpy).toHaveBeenCalled();
	expect(warnSpy.mock.calls[0][0]).toContain("ALERT");
});

test("debug() calls console.debug", () => {
	logger.debug("debug message");
	expect(debugSpy).toHaveBeenCalled();
	expect(debugSpy.mock.calls[0][0]).toContain("DEBUG");
});

test("error() handles strings and Error objects with stack traces", () => {
	logger.error("simple error");
	expect(errorSpy).toHaveBeenCalled();
	expect(errorSpy.mock.calls[0][0]).toContain("ERROR");

	const testErr = new Error("failed task");
	logger.error("ignored", testErr);
	const output = errorSpy.mock.calls[1][0];
	expect(output).toContain("failed task");
	expect(output).toContain("└─");
});

test("sanitizeStack filters node_modules and formats paths", () => {
	const fakeStack = `Error: msg
            at Object.<anonymous> (/dev/project/index.ts:10:5)
            at Module._compile (node_modules/module.js:1:1)
            at internal/main.js:2:2`;

	const err = new Error("msg");
	err.stack = fakeStack;

	const output = logger.notif(err, true) as string;

	expect(output).toContain("index.ts");
	expect(output).toContain("(L10 C5)");
	expect(output).not.toContain("node_modules");
});

test("divider() prints a centered string", () => {
	logger.divider("TEST");
	expect(logSpy).toHaveBeenCalled();
	const output = logSpy.mock.calls[0][0];
	expect(output).toContain("TEST");
	expect(output).toContain("─");
});

test("timestamp format matches expected pattern", () => {
	const output = logger.notif("time check", true) as string;
	// Matches [Day HH:mm:ss.ms] using gray color codes
	expect(output).toMatch(/\[.*?\d{2}:\d{2}:\d{2}\.\d{3}\]/);
});
